apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: csharpwars-key-vault
  namespace: default
spec:
  vault:
    name: gebakv
    object:
      name: key-vault
      type: secret
  output:
    secret: 
      name: csharpwars-key-vault
      dataKey: KEY_VAULT
      type: opaque
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: csharpwars-client-id
  namespace: default
spec:
  vault:
    name: gebakv
    object:
      name: client-id
      type: secret
  output:
    secret: 
      name: csharpwars-client-id
      dataKey: CLIENT_ID
      type: opaque
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: csharpwars-client-secret
  namespace: default
spec:
  vault:
    name: gebakv
    object:
      name: client-secret
      type: secret
  output:
    secret: 
      name: csharpwars-client-secret
      dataKey: CLIENT_SECRET
      type: opaque

    